version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: "maven"
    directories:
      - "/"
      - "/magik-checks"
      - "/magik-debug-adapter"
      - "/magik-language-server"
      - "/magik-lint"
      - "/magik-squid"
      - "/magik-typed-checks"
      - "/magik-typed-lint"
      - "/sonar-magik-plugin"
      - "/sslr-magik-toolkit"
    schedule:
      interval: monthly
  - package-ecosystem: "npm"
    directory: "magik-language-server/client-vscode"
    schedule:
      interval: monthly
