version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: "npm"
    directory: "magik-language-server/client-vscode"
    schedule:
      interval: monthly
