name: Publish checks to wiki
on:
  push:
    branches: [develop]
    paths:
      - .github/workflows/publish-checks-wiki.yml
      - .github/scripts/generate-checks-pages.py
      - magik-checks/src/main/resources/nl/ramsolutions/sw/sonar/l10n/magik/rules/*.html
      - magik-checks/src/main/java/nl/ramsolutions/sw/magik/checks/checks/*Check.java
concurrency:
  group: publish-checks-wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install html2text==2024.2.26
          python3 .github/scripts/generate-checks-pages.py
      - uses: Andrew-Chen-Wang/github-wiki-action@86138cbd6328b21d759e89ab6e6dd6a139b22270
        with:
          path: wiki
          #dry-run: true
        if: ${{ github.repository_owner == 'StevenLooman' }}
